### ISSUE TITLE
Not able to build the mediapipe library as bazel cannot locate visual studio

### ISSUE THREAD

**Issue by vsingh1986** [cpvrlab/libmediapipe#10]
Thanks for creating and sharing the mechanism to build shared library of mediapipe. I really need it for my Cmake build. 

I am trying to run the code to create the build but the i continuously get following error.

ERROR: C:/users/vivek/_bazel_vivek/wceexvqj/external/com_google_protobuf/BUILD:420:11: Compiling src/google/protobuf/compiler/csharp/csharp_primitive_field.cc [for host] failed: (Exit 1): vc_installation_error_x64.bat failed: error executing command
  cd /d C:/users/vivek/_bazel_vivek/wceexvqj/execroot/mediapipe
  SET INCLUDE=clang_cl_not_found
    SET PATH=clang_cl_not_found
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=clang_cl_not_found
    SET TMP=clang_cl_not_found
  external\local_config_cc\vc_installation_error_x64.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/com_google_protobuf /Ibazel-out/host/bin/external/com_google_protobuf /Iexternal/zlib /Ibazel-out/host/bin/external/zlib /Iexternal/com_google_protobuf/src /Ibazel-out/host/bin/external/com_google_protobuf/src /Iexternal/zlib /Ibazel-out/host/bin/external/zlib /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -Wno-builtin-macro-redefined /Gy /Gw /D_USE_MATH_DEFINES /std:c++17 -DHAVE_ZLIB -Wmissing-field-initializers -Woverloaded-virtual -Wno-sign-compare /Fobazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_primitive_field.obj /c external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_primitive_field.cc
# Configuration: 41b8ff91e4236ab9647f22a210ba7e953e8d853981c3847b13823c101adb7ed9
# Execution platform: @local_execution_config_platform//:platform

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.
Please check your installation following https://docs.bazel.build/versions/main/windows.html#using

I am using basel 5.2 and visual studio 2022, on windows 10. i have already i installed clang. I am not a professional software developer, need this for some personal use. 
Appreciate your help thanks.

**Comment by chnoblouch** [comment]
The problem might be that you installed Visual Studio without C++ build tools. When you open the Visual Studo Installer and click _Modify_ on your installation, is the checkbox ticked for _Desktop development with C++_?

**Comment by vsingh1986** [comment]
Thanks dear, i was able to build the mediapipe library and run your example. 
I was able to integrate the library in my project.
