### ISSUE TITLE
Build Failed on Fedora

### ISSUE THREAD

**Issue by vishal-ahirwar** [cpvrlab/libmediapipe#8]
I'm using fedora 40  and I installed all the dependencies 
The error I'm getting
`ERROR: /home/vishalahirwar/.cache/bazel/_bazel_vishalahirwar/dbbac8821b8211cc41bb4f6f8e43ad32/external/flatbuffers/src/BUILD.bazel:34:11: Compiling src/bfbs_gen_lua.cpp [for host] failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 24 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from bazel-out/host/bin/external/flatbuffers/src/_virtual_includes/flatbuffers/flatbuffers/array.h:21,
                 from bazel-out/host/bin/external/flatbuffers/src/_virtual_includes/flatbuffers/flatbuffers/flatbuffers.h:22,
                 from bazel-out/host/bin/external/flatbuffers/src/_virtual_includes/flatbuffers/flatbuffers/reflection_generated.h:7,
                 from external/flatbuffers/src/bfbs_gen.h:23,
                 from external/flatbuffers/src/bfbs_gen_lua.cpp:27:
bazel-out/host/bin/external/flatbuffers/src/_virtual_includes/flatbuffers/flatbuffers/stl_emulation.h: In member function 'constexpr flatbuffers::span<T, Extent>& flatbuffers::span<T, Extent>::operator=(const flatbuffers::span<T, Extent>&)':
bazel-out/host/bin/external/flatbuffers/src/_virtual_includes/flatbuffers/flatbuffers/stl_emulation.h:386:12: error: assignment of read-only member 'flatbuffers::span<T, Extent>::count_'
  386 |     count_ = other.count_;
      |     ~~~~~~~^~~~~~~~~~~~~~
Target //mediapipe/c:mediapipe failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 44.262s, Critical Path: 25.57s
INFO: 168 processes: 136 internal, 32 linux-sandbox.
FAILED: Build did NOT complete successfully
`

**Comment by chnoblouch** [comment]
Hi @vishal-ahirwar, sorry for not responding sooner. Which versions of MediaPipe and GCC are you using?

**Comment by vishal-ahirwar** [comment]
Hi @chnoblouch  it went well after little bit of modification in build script so I'm closing this issue
